---
- name: Deploy docker images
  hosts: localhost

  tasks:
    - name: Copy Docker Compose file from host machine to remote host
      copy:
        src: ./docker-compose.yml
        dest: ./

    - name: Pull the Docker images specified in docker-compose
      shell:
        cmd: sudo docker compose pull
        chdir: ./

    - name: Run the pulled Docker images in detached mode
      command: sudo docker compose up -d --build
      args:
        chdir: ./